def serviceScmUrl = "https://github.com/kirilla111/home-server.git"
def serviceBranchName = "master"
def appDirName = "app"

pipeline {
    agent any

    stages {
        stage('checkout'){
            steps{
                echo "checkout master branch ------------------>"
                     checkout scm: [
                                    $class           : 'GitSCM',
                                    branches         : [[name: "${serviceBranchName}"]],
                                    userRemoteConfigs: [
                                            [
                                                    credentialsId: 'ed596ff2-951e-4fad-9018-20741c763036',
                                                    url          : "${serviceScmUrl}"
                                            ]
                                    ]
                            ]
            }
        }

        stage("Сборка и тестирование") {
            agent {
                 docker {
                    image 'gradle:8.1.1-jdk17'
                    reuseNode true
                 }
            }
            steps{
                withGradle {
                    dir("${appDirName}") {
                        sh './gradlew clean build'
                    }
                }
            }
        }

        stage('hello') {
            steps {
                sh 'docker -v'
            }
        }
    }
}